nelmio_api_doc:
    documentation:
        info:
            title: "🧃 Vending Machine API"
            version: "1.0.0"
            description: "API for vending machine system"

    html_config:
        assets_mode: cdn
        swagger_ui_config:
            docExpansion: list
            displayRequestDuration: true
            filter: true
            tryItOutEnabled: true
            persistAuthorization: true
