services:
  tests:
    image: vending_machine_test
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - mysql_test
    environment:
      APP_ENV: test
      DATABASE_URL: mysql://vending:vending@mysql_test:3306/vending_machine_test
    command: vendor/bin/phpunit
