services:
  mysql_test:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: vending_machine_test
      MYSQL_USER: vending
      MYSQL_PASSWORD: vending
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  tests:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - mysql_test
    environment:
      APP_ENV: test
      DATABASE_URL: mysql://vending:vending@mysql_test:3306/vending_machine_test
    command: vendor/bin/phpunit
