services:
  tests:
    image: vending_machine_test
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - mysql_test
    environment:
      APP_ENV: test
      DATABASE_URL: mysql://vending:vending@mysql_test:3306/vending_machine_test
    command: vendor/bin/phpunit

  mysql_test:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vending_machine_test
    volumes:
      - ./docker/mysql/init-test.sql:/docker-entrypoint-initdb.d/init.sql
