# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\VendingMachine\Domain\:
        resource: '../src/VendingMachine/Domain/'

    App\VendingMachine\Infrastructure\Controller\:
        resource: '../src/VendingMachine/Infrastructure/Controller/'
        tags: ['controller.service_arguments']

    App\VendingMachine\Infrastructure\:
        resource: '../src/VendingMachine/Infrastructure/'
        exclude:
            - '../src/VendingMachine/Infrastructure/Controller/'

    App\VendingMachine\Application\:
        resource: '../src/VendingMachine/Application/'
        public: true
        exclude:
            - '../src/VendingMachine/Application/TransactionResultDTO.php'
            - '../src/VendingMachine/Application/Client/Command'
            - '../src/VendingMachine/Application/Tecnician/Command'
            - '../src/VendingMachine/Application/Tecnician/Change/RefillChangeReponse.php'
