.PHONY: help

help:
	@echo "$(IRed)"
	@fgrep -h "###" ./make/head.mk | fgrep -v fgrep | sed -e 's/\\	$$//' | sed -e 's/###//'
	@echo "$(Color_Off)"
	@echo ""
	@echo "   $(BCyan)help:                 $(Color_Off)This help"
	@echo ""
	@echo "   $(BCyan)init:                 $(Color_Off)Initialize docker"
	@echo "   $(IPurple)Docker$(Color_Off)"
	@echo "   $(BCyan)up:                   $(Color_Off)Initialize dokcer with build"
	@echo "   $(BCyan)down:                 $(Color_Off)Shutdown docker"
	@echo "   $(BCyan)build:                $(Color_Off)Build images"
	@echo "   $(BCyan)install:              $(Color_Off)Execute composer install"
	@echo "   $(BCyan)clear:                $(Color_Off)Clear Symfony cache"
	@echo "   $(IPurple)DB$(Color_Off)"
	@echo "   $(BCyan)db-init:              $(Color_Off)Intialize BD, used in init"
	@echo "   $(BCyan)db-reset:             $(Color_Off)Reset the BD (delete all previous info)"
	@echo "   $(IPurple)Testing$(Color_Off)"
	@echo "   $(BCyan)test:                 $(Color_Off)Execute all test"
	@echo "   $(BCyan)test-unit:            $(Color_Off)Execute ONLY Unit test"
	@echo "   $(BCyan)test-functional:      $(Color_Off)Execute ONLY Functional test"
	@echo "   $(BCyan)test-integration:     $(Color_Off)Execute ONLY integration test (use SQLlite)"
	@echo "   $(BCyan)coverage:             $(Color_Off)Generate coverage"
	@echo "   $(IPurple)Quality$(Color_Off)"
	@echo "   $(BCyan)cs:                   $(Color_Off)Execute cs-fixer"
	@echo "   $(BCyan)cs-dry:               $(Color_Off)Execute cs-fixer without changes"
	@echo "   $(BCyan)phpstan:              $(Color_Off)Execute phpstan"
	@echo "   $(BCyan)quality:              $(Color_Off)Execute all quality tools"
	@echo ""
